input-output-hk/catalyst-core

src/chain-libs/.envrc
src/chain-libs/.gitignore
src/chain-libs/flake.lock
src/chain-libs/flake.nix

Adds a flake.nix to chain libs. Note, this doesn't have any outputs, it just provides a `devShell` so you can run `cargo build` on a nixos machine
Also adds direnv integration

add flake to chain libs

---

src/jormungandr/explorer/src/db/indexing.rs
src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/certificates.rs

_explorer_update_proposal_certificate_test()_  covers _**update_proposal**_ and _**update_vote**_

add missing fragments

---

src/chain-libs/chain-crypto/src/digest.rs
src/chain-libs/chain-crypto/src/testing.rs
src/chain-libs/chain-evm/src/transaction.rs
src/chain-libs/chain-impl-mockchain/src/lib.rs
src/chain-libs/chain-network/src/lib.rs

Removes a few unsafe `Send` impls in chain-libs
A quick look doesn't reveal any unsoundness, since there were other `Send` bounds in places where they should be, but it's a much more fragile solution than relying on auto traits to get the implementation
Also fixes a few clippy errors

remove unsafe send impls

---

src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/mod.rs

[ExplorerProcess](https://github.com/input-output-hk/catalyst-core/blob/426dc2fd7dce89d0943a4433805c0ebf74ed28f1/src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/mod.rs#L54) logs were being only partially captured by the stdout pipe and written to `/tmp/jormungandr_*/explorer.log`. I'm assuming this is a buffering problem. This PR changes the Explorer's child process spawning code to capture its output to a file which seems to fix that problem.
I also did some refactoring.

Fix explorer process incomplete logs in integration tests

---

src/vit-servicing-station/doc/api/v0.yaml

Added a description about a new endpoint, which is supposed to be used for submitting proposals fetched from the ideascale service

Describe new /api/v0/admin/proposals API endpoint

---

src/vit-testing/vitup/src/mode/mock/context.rs

properly reset context in rest api. Fix dockers to use main version of catalyst-core

Attempt to fix vitup mock memory leaks problem

---

src/vit-servicing-station/doc/api/v0.yaml
src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/challenges.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/challenges/handlers.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/challenges/logic.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/challenges/routes.rs

Adding new `/api/v0/challenges/{id}/{voter_group_id}` endpoint which acts mostly the same as `/api/v0/challenges/{id}` but also filtering proposals by `voter_group_id`

Implement new /api/v0/challenges/{id}/{voter_group_id} endpoint

---

src/jormungandr/explorer/src/api/graphql/mod.rs
src/jormungandr/explorer/src/db/mod.rs
src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/all_vote_plans_verifier.rs
src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/vote_plan_verifier.rs
src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/vote_plan.rs

- Update the public tally every time a vote is cast. Rather than waiting for the voting to end before being able to check tally results; mainly for _transparency_. 
- The rest of the PR addresses private tally return values in the None case _(3369)._

Npg 3808 tally per vote cast

---

src/vit-servicing-station/vit-servicing-station-cli/src/api_token.rs
src/vit-servicing-station/vit-servicing-station-cli/src/init_db.rs
src/vit-servicing-station/vit-servicing-station-lib/Cargo.toml
src/vit-servicing-station/vit-servicing-station-lib/src/db/migrations.rs
src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/api_tokens.rs
src/vit-servicing-station/vit-servicing-station-lib/src/testing/filters.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/api_token.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/funds/handlers.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/votes/handlers.rs
src/vit-servicing-station/vit-servicing-station-tests/src/common/paths.rs

vit-ss used to embed the migration files but after [these changes](https://github.com/input-output-hk/catalyst-core/commit/586ae82961c79894f251d148a5a7cbd04c31b21e#diff-e125a6865c74aefe3235510a1fbb72cded9672ac918e9be8214466a53a0ac1c1L3) migration files were being read from relative directories which broke things.
This makes the vit-ss CLI init db command work correctly again and also fixes the vit-ss integration tests (still testing only SQLite).
*PS: Since diesel migrations lib seems to only provide functions for running migrations that receive directory paths as arguments, I decided to embed the migration files and write them to a temporary directory when running the migrations. Not sure if this is the best solution.*

Embed vit-ss migration files

---

.github/workflows/ci_tests.yml

Adds back the tests for non-jormungandr crates
Also re-enables fail-fast

Add remaining tests

---

src/catalyst-toolbox/catalyst-toolbox/src/rewards/dreps.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/voters.rs
src/vit-servicing-station/vit-servicing-station-tests/src/common/data/generator/arbitrary/snapshot_generator.rs

An issue for extracting the correct bytes from a hex-encoded string is resolved.
The fix was added to convert the 64-character hex-encoded digest of a Blake2b256 into the underlying 32-byte array used to define the `chain_proposal_id` field of the `FullProposalInfo` type.

fix hex-encoded string conversion for chain_proposal_id

---

src/chain-wallet-libs/hdkeygen/src/rindex/hdpayload.rs

- Fix chain-wallet-libs tests after bip39 removal

Fix chain-wallet-libs tests

---

nix/automation/configs.nix
nix/automation/devshells.nix

Pre commit hooks get installed without warning when running a nix dev shell.  This has the effect of changing the development environment outside the dev shell.
The pre-commit hooks do not take into consideration the local developers environment or tooling, such as IDE of choice.  Also, the pre-commit hooks assume tooling which may only be present inside the dev shell.  This can lead to an inability to commit and interferes with local development.
This patch removes that, so that running the dev shell does not change the development environment outside the dev shell.

do not install pre-commit hooks

---

src/chain-libs/chain-impl-mockchain/src/account.rs
src/chain-libs/chain-impl-mockchain/src/accounting/account/spending.rs
src/chain-libs/chain-impl-mockchain/src/ledger/recovery.rs
src/chain-wallet-libs/bindings/wallet-core/src/c/mod.rs
src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
src/chain-wallet-libs/wallet/src/account.rs
src/chain-wallet-libs/wallet/tests/account.rs
src/jormungandr/jormungandr-lib/src/interfaces/account_state.rs
src/jormungandr/testing/thor/src/cli/config.rs
src/jormungandr/testing/thor/src/cli/controller.rs
src/jormungandr/testing/thor/src/cli/error.rs
src/jormungandr/testing/thor/src/cli/wallet_controller.rs
src/jormungandr/testing/thor/src/wallet/account.rs
src/jormungandr/testing/thor/src/wallet/mod.rs
src/vit-testing/iapyx/src/controller/mod.rs
src/vit-testing/iapyx/src/load/multi_controller.rs
src/vit-testing/iapyx/src/wallet.rs

Refactor SpendingCounter implementation. Replace Vec with an array usage.
At this place we are certanly know what is the size of SpendingCountersIncresing lanes, so it is better replace dynamic sized collection with the static sized collection.
Been fixed only existing tests,  no any new tests been added

Refactor SpendingCounter, replace Vec usage with array

---

src/jormungandr/jormungandr-lib/src/interfaces/config/mod.rs
src/jormungandr/jormungandr-lib/src/interfaces/config/node.rs
src/jormungandr/jormungandr/src/settings/start/config.rs
src/jormungandr/jormungandr/src/settings/start/mod.rs
src/jormungandr/testing/hersir/src/builder/explorer.rs
src/jormungandr/testing/hersir/src/builder/settings/mod.rs
src/jormungandr/testing/hersir/src/config/spawn_params.rs
src/jormungandr/testing/hersir/src/controller/mod.rs
src/jormungandr/testing/jormungandr-automation/src/jormungandr/configuration/node/manager.rs
src/jormungandr/testing/jormungandr-automation/src/jormungandr/configuration/node/node_config_builder.rs
src/jormungandr/testing/jormungandr-automation/src/jormungandr/legacy/config/node/mod.rs
src/jormungandr/testing/jormungandr-integration-tests/src/networking/p2p/connections.rs
src/jormungandr/testing/jormungandr-integration-tests/src/networking/p2p/public_traffic.rs
src/jormungandr/testing/jormungandr-integration-tests/src/networking/p2p/quarantine.rs

Currently the p2p config has become cluttered with multiple behaviours; i.e internode relations, bootstrap info and other things. PR adds extra sub settings to logically separate the functionality for clarity and context.

logically seperate p2p config

---

.github/workflows/nix.yml

This will prevent upstream changes from breaking CI, which just recently happened.

build: locks std-action to v0.0.2

---

nix/vit-servicing-station/operables.nix

The vit servicing station server exits silently if this configuration parameter is missing. We set it to an empty string here because it's passed as a flag during runtime.

build: adds missing config setting for vit-ss

---

nix/jormungandr/containers.nix
nix/vit-servicing-station/containers.nix
scripts/login-ecr.sh
scripts/push-image.sh

Dirty git repositories now resort to using the output hash as the tag (to prevent overriding someone else's testing), and two scripts have been added for pushing images:
- `scripts/login-ecr.sh`: Authenticates to ECR
- `scripts/push-image.sh`: Pushes an image to ECR (use `-l` to view a list of all image names)
Appropriate AWS accounts will need to be set up to use this.

build: adds scripts for pushing images

---

src/election-db/migrations/2022-12-01-043118_vit-ss/up.sql

These were some issues I found while testing the DB schema against the current vit-ss build.
Converting timestamps to BIGINT is needed because vit-ss uses BIGINT to store timestamps and `EXTRACT(EPOCH FROM somecolumn)` gives a floating point number containing the Unix timestamp in its integral part.

Make timestamps BIGINT and some other adjustments

---

book/src/core-vitss-doc/api/v0.yaml

[/snapshot/delegator/](https://github.com/input-output-hk/catalyst-core/blob/3f64ee55fa0055eb8e45a27b136290b129578094/book/src/core-vitss-doc/api/v0.yaml#L336) should $ref [DelegatorInfo](https://github.com/input-output-hk/catalyst-core/blob/3f64ee55fa0055eb8e45a27b136290b129578094/book/src/core-vitss-doc/api/v0.yaml#L1170) not [VotersInfo](https://github.com/input-output-hk/catalyst-core/blob/3f64ee55fa0055eb8e45a27b136290b129578094/book/src/core-vitss-doc/api/v0.yaml#L1016), 
I think VotersInfo was just copied from /snapshot/voter/ endpoint.
cc: @stevenj

docs: fixed reference in VIT-SS API docs

---

.github/workflows/js_wallet_publish.yml
Cargo.lock
src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json

Update wallet-js package publishing, change wasm target from `nodejs` to `web`. Modify modules managing approach from `CommonJs` to `ES` standard.

Fix wallet-js publishing

---

Cargo.lock
Cargo.toml
src/chain-libs/chain-vote/Cargo.toml
src/jortestkit/Cargo.toml
src/vit-servicing-station/vit-servicing-station-cli/Cargo.toml
src/vit-servicing-station/vit-servicing-station-tests/Cargo.toml
src/vit-testing/iapyx/Cargo.toml
src/vit-testing/integration-tests/Cargo.toml
src/vit-testing/mainnet-tools/Cargo.toml
src/vit-testing/scheduler-service-lib/Cargo.toml
src/vit-testing/snapshot-trigger-service/Cargo.toml
src/vit-testing/vitup/Cargo.toml
src/voting-tools-rs/src/model/mod.rs

Reverts input-output-hk/catalyst-core#212
Fixes nix builds. Will troubleshoot why it broke them at a later time.

Revert "Dedup 7"

---

nix/vit-servicing-station/operables.nix

Since we're using SQLite for the next SVE, this allows us to use a local database file temporarily and still support testing with PostgreSQL.

build: defaults vit-ss to use sqlite if pgsql url is absent

---

src/catalyst-toolbox/catalyst-toolbox/src/recovery/tally.rs
src/chain-libs/chain-impl-mockchain/src/transaction/witness.rs
src/chain-wallet-libs/bindings/wallet-core/src/tx_builder.rs
src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
src/chain-wallet-libs/bindings/wallet-wasm-js/tests/certificates/vote_cast.rs
src/chain-wallet-libs/bindings/wallet-wasm-js/tests/certificates/vote_plan.rs
src/chain-wallet-libs/bindings/wallet-wasm-js/tests/lib.rs
src/chain-wallet-libs/wallet/src/account.rs
src/chain-wallet-libs/wallet/src/transaction/builder.rs
src/chain-wallet-libs/wallet/src/transaction/mod.rs
src/chain-wallet-libs/wallet/src/transaction/witness_builder.rs
src/chain-wallet-libs/wallet/tests/account.rs

Fixes this issue https://github.com/input-output-hk/catalyst-core/issues/225. 
Provide a capability for the wallet js to sign transaction by its own without using our api.

Update wallet js tx building process, refactor WitnessBuilder

---

Cargo.lock
Cargo.toml
src/catalyst-toolbox/catalyst-toolbox/Cargo.toml
src/catalyst-toolbox/snapshot-lib/Cargo.toml
src/jormungandr/testing/jormungandr-automation/Cargo.toml
src/voting-tools-rs/src/validation/tests.rs

Attends critical audit alert caused by the `failure` crate. `graphql_client v0.12` removes that crate.

Fix graphql client version

---

src/vit-testing/vitup/src/mode/service/manager/file_lister.rs

Compilation fails with serde 1.0.157 https://github.com/serde-rs/serde/issues/2415
Removing empty serde annotation fixes the issue

fix: Serde empty annotations bug 

---

utilities/ideascale-importer/README.md
utilities/ideascale-importer/ideascale_importer/__main__.py
utilities/ideascale-importer/ideascale_importer/app.py
utilities/ideascale-importer/poetry.lock
utilities/ideascale-importer/pyproject.toml

Adds an executable script `ideascale-importer` to the `ideascale_importer` python package in `utilities/ideascale-importer`.

feat: Add 'ideascale-importer' script to ideascale_importer package

---

utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
utilities/ideascale-importer/ideascale_importer/ideascale/client.py
utilities/ideascale-importer/ideascale_importer/ideascale/importer/__init__.py

This PR adds a new CLI arg to the IdeaScale data importer to customize IdeaScale API. Now you can do:
```
poetry run python -m ideascale_importer ideascale import-all \
[...] \ 
--ideascale-api-url https://someideascale.api.com
```

refactor: Make IdeaScale API configurable in IdeaScale data importer

---

Cargo.lock
Cargo.toml
Makefiles/db.toml
book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/Cargo.toml
src/cat-data-service/src/service/v1/event.rs
src/cat-data-service/src/service/v1/mod.rs
src/cat-data-service/src/service/v1/registration.rs
src/cat-data-service/src/state.rs
src/event-db/Cargo.toml
src/event-db/migrations/V3__objective_tables.sql
src/event-db/src/queries/event.rs
src/event-db/src/queries/mod.rs
src/event-db/src/queries/registration.rs
src/event-db/src/types/event.rs
src/event-db/src/types/mod.rs
src/event-db/src/types/registration.rs
src/event-db/src/types/utils.rs
src/event-db/test_data/event_table.sql
src/event-db/test_data/goal_table.sql
src/event-db/test_data/voting_group_table.sql

Implement new event's endpoints `/api/v1/events` and `'/api/v1/event/{id}'` with the corresponded db queries and db types.
https://github.com/input-output-hk/catalyst-core/blob/98c8b0298607ca255fac6b6536188aba5918be05/book/src/07_web_api/openapi/core_backend_api.yaml#L74
This PR does not contain a full implementation, it will be needed to implement sql queries for `registration`, `goals` and `groups` fields of the `EventDetails` struct. This will be done in the next PRs
- New feature (non-breaking change which adds functionality)
**List of new dependecies**: 
- `rust_decimal`: needed to parse postgressql `numeric` type

feat: NPG-5790, NPG-5815 add new event's endpoint and db queries

---

.github/workflows/rust.yml
Makefiles/db.toml
book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/event/mod.rs
src/cat-data-service/src/service/v1/event/objective.rs
src/cat-data-service/src/service/v1/registration.rs
src/event-db/migrations/V5__vote_plan.sql
src/event-db/src/lib.rs
src/event-db/src/queries/event/mod.rs
src/event-db/src/queries/event/objective.rs
src/event-db/src/queries/mod.rs
src/event-db/src/queries/registration.rs
src/event-db/src/types/event/objective.rs

Last part of the /api/v1/event/{id}/objectives endpoint implementation.
At this moment `ballot: GroupBallotType` field is omitted and mocked data just returned. It will be fixed later after deep investigation on the `voteplan` or `objective` tables.

feat: NPG-5816 /api/v1/event/{id}/objectives endpoint (part 2)

---

containers/event-db-graphql/entry.sh
containers/event-db-migrations/Earthfile
containers/event-db-migrations/entry.sh
services/voting-node/docker-compose.yml
src/event-db/setup/dev-db.docker-compose.yml
src/event-db/setup/graphql-setup.sql

Improves the entrypoint script for the migrations container by:
- Adding common bash options
- Adding support for debugging and sleeping
- Documenting the expected environment variables
- Allowing skipping steps of initialization (creating the database/user is not required in Kubernetes)
- Inheriting from base builder/deployment images to be consistent with other containers
- Running commands as expected database user
Additionally, this PR modifies the SQL setup script to stop printing passwords to `stdout`. Note that container logs will reflect anything in `stdout` and are, by default, exported to Loki. We should, therefore, avoid printing any sensitive values to `stdout`. You can still set the `DEBUG` environment variable and the passwords will show up in the printed SQL commands. …

refactor: Makes migrations more configurable

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
src/event-db/src/queries/event/objective.rs
src/event-db/src/queries/event/proposal.rs
src/event-db/src/types/event/objective.rs
src/event-db/src/types/event/proposal.rs

- updated current proposal and objective types, removed all ballot specific information
- added a new `CatalystV1Ballot` type
- added a new ballot API endpoints: `/api/v1/event/{id}/ballots`, `/api/v1/event/{id}/objective/{obj_id}/ballots`, `/api/v1/event/{id}/objective/{obj_id}/proposal/{prop_id}/ballot`

feat: Add new Ballot API

---

src/cat-data-service/src/service/v1/event/ballots.rs
src/cat-data-service/src/service/v1/event/mod.rs
src/cat-data-service/src/service/v1/event/objective/ballots.rs
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/ballot.rs
src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs

Added following endpoint to the cat-data-service:
- `/api/v1/event/{id}/objective/{obj_id}/proposal/{prop_id}/ballot`
- `/api/v1/event/{id}/objective/{obj_id}/ballots`
- `/api/v1/event/{id}/ballots`

feat: Add ballot endpoints to the cat data service | NPG-6556

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/event/ballots.rs
src/cat-data-service/src/service/v1/event/mod.rs
src/cat-data-service/src/service/v1/event/objective/ballots.rs
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/ballot.rs
src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/review.rs
src/cat-data-service/src/service/v1/event/objective/review_type.rs
src/cat-data-service/src/service/v1/registration.rs
src/cat-data-service/src/service/v1/search.rs
src/event-db/migrations/V4__proposal_tables.sql
src/event-db/src/queries/event/review.rs
src/event-db/src/types/event/review.rs

Refactored cat-data-service tests, updated assertions checks with the json representation of the returning object without using explicit Rust db types. It allows to test precisely by our API specification, instead of using our Rust internal db types serde.
Also updated `map` field of the `ReviewType` from string to object.
Updated `review_metric` chema, `map` column from `JSONB` to `JSONB ARRAY`

refactor: Cat-data-service tests update | NPG-6632

---

src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/kedqr/decode/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/kedqr/encode/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/kedqr/info.rs

Fixing a bug in this cat-toolbox cmd
```
catalyst-toolbox qr-code info --input wallet_2_above_500_1234.png --pin 1234 --opts img
The application panicked (crashed).
Message:  Mismatch between definition and access of pin. Could not downcast to TypeId { t: 3006200894326385576 }, need to downcast to TypeId { t: 4144576253896540664 }
```

fix: Fix pin type | NPG-6509

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/health.rs
src/cat-data-service/src/service/mod.rs

Added health check endpoints for cat-data-service:
- `/health/live` - liveness of the service endpoint
- `/health/ready` - readiness of the service to accept incoming requests endpoint

feat: Cat-data-service health endpoints | NPG-6603

---

src/cat-data-service/src/service/mod.rs
src/cat-data-service/src/service/v1/event/ballots.rs
src/cat-data-service/src/service/v1/event/objective/ballots.rs
src/cat-data-service/src/service/v1/event/objective/proposal/ballot.rs
src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/review.rs
src/cat-data-service/src/service/v1/search.rs
src/event-db/src/queries/event/ballot.rs
src/event-db/src/queries/event/proposal.rs
src/event-db/src/queries/event/review.rs
src/event-db/src/queries/search.rs
src/event-db/src/types/event/proposal.rs
src/event-db/test_data/08_proposal_table.sql

- Fixed `get_proposal` query, slightly updated tests
- Updated responded error message from the cat-data-service, so now instead of returning just a string, it  returns a `{error: "some error" }` json object.

fix: Fix get_proposal query, updated responded error message | NPG-6702

---

src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/dreps.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/lib.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/dreps.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/proposers/io.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/proposers/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/voters.rs
src/catalyst-toolbox/catalyst-toolbox/src/types/challenge.rs
src/catalyst-toolbox/catalyst-toolbox/src/types/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/types/proposal.rs
src/vit-testing/integration-tests/src/e2e/local/active_voters_rewards.rs
src/vit-testing/integration-tests/src/e2e/rewards/drep_rewards.rs
src/vit-testing/integration-tests/src/e2e/rewards/rewards_scenarios.rs
src/vit-testing/integration-tests/src/e2e/rewards/voter_rewards.rs

Removed usage of some vit-ss types as `Proposal`, `Challenge`, `FullProposalInfo`, replaced it with the new corresponded internal catalyst-toolbox types

refactor: Replace the usage of some vit-ss types inside catalyst-toolbox | NPG-6766

---

src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/community_advisors.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/dreps.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/full/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/proposers/mod.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/voters.rs
src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/stats/archive.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/proposers/io.rs
src/catalyst-toolbox/catalyst-toolbox/src/rewards/proposers/types.rs
src/catalyst-toolbox/catalyst-toolbox/src/testing.rs
src/catalyst-toolbox/catalyst-toolbox/src/utils/csv.rs
src/catalyst-toolbox/catalyst-toolbox/src/utils/mod.rs

Removed vit-ss server usage from catalyst-toolbox cli tool for gathering proposer's rewards. So right now all needed information should be passed by files

refactor: Remove vit-ss server usage from catalyst-toolbox | NPG-6766

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/registration.rs
src/event-db/migrations/V6__snapshot_tables.sql
src/event-db/src/queries/registration.rs
src/event-db/src/types/registration.rs
src/event-db/test_data/04_contribution_table.sql

Added a new `reward_address` field for the delegation type for the `/api/v1/registration/delegations/{sp_key}` endpoint.
Fixed and improved delegation's queries.

feat: Add `reward_address` field for the Delegation endpoint | NPG-6785

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/registration.rs
src/event-db/src/queries/registration.rs
src/event-db/src/types/registration.rs

Added a new optional query parameter `with_delegators` for ` /api/v1/registration/voter/{vkey}` endpoint. Which returns `delegators_addresses` list in response if enabled.

feat: Add delegators addresses list as a response to the `/api/v1/registration/voter/{vkey}` endpoint | NPG-6804

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/Cargo.toml
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/event-db/src/types/event/mod.rs
src/event-db/src/types/event/voting_status.rs

Added `/api/v1/event/{id}/objectives/voting_status` new endpoint, which returns all votings statuses related to each objective per provided event_id. Currently this endpoint returns a mocked data, because right now we dont have it inside event db, it will be updated later.

feat: Add new voting status endpoint | NPG-6955

---

src/cat-data-service/src/main.rs
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/cat-data-service/src/types/mod.rs
src/cat-data-service/src/types/objective.rs
src/cat-data-service/src/types/voting_status.rs
src/event-db/src/queries/event/objective.rs
src/event-db/src/types/event/objective.rs
src/event-db/src/types/event/voting_status.rs

Moving serde implementation of the types which are cunsumed by the cat-data-service directly into the cat-data-service from event-db. 
It makes cat-data-service independent from the event-db of how represent the data while we are returning it in responses.

refactor: Move serde definiton from event-db to cat-data-service (Part 1) | NPG-7002

---

src/cat-data-service/Cargo.toml
src/cat-data-service/src/service/v1/event/mod.rs
src/cat-data-service/src/types/event.rs
src/cat-data-service/src/types/mod.rs
src/event-db/src/types/event/mod.rs

Moving serde implementation of the types which are cunsumed by the cat-data-service directly into the cat-data-service from event-db.
It makes cat-data-service independent from the event-db of how represent the data while we are returning it in responses.

refactor: Move serde definiton from event-db to cat-data-service (Part 3) | NPG-7002

---

src/cat-data-service/src/service/mod.rs

Seting `Access-Control-Allow-Headers` to the cors heder responses, needed for requests with `Access-Control-Request-Headers` value.

fix: Add `Access-Control-Allow-Headers` cors header | NPG-0000

---

utilities/ideascale-importer/ideascale_importer/ideascale/client.py
utilities/ideascale-importer/ideascale_importer/utils.py

* Fixed the issue with `ideascale.Client.stage_ideas` throwing 1 stage not found exception for each download task worker (now it throws only 1)

fix: IdeaScale importer no longer one exception for each worker when fetching stage ideas | NPG-6949

---

utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
utilities/ideascale-importer/ideascale_importer/ideascale/client.py
utilities/ideascale-importer/ideascale_importer/ideascale/importer.py

- Fixed proposals not being filtered by campaign id when writing them to the DB which was causing an exception
- Fixed campaigns not being found caused by a filter on the campaign name
- Some other minor fixes
```
poetry run ideascale-importer ideascale import-all --api-token API_KEY --database-url DBURL --ideascale-api-url https://temp-cardano-sandbox.ideascale.com  --event-id 1 --campaign-group-id 87 --stage-id 1
```
Imported 0 proposals as expected.
```
poetry run ideascale-importer ideascale import-all --api-token API_KEY --database-url DBURL --ideascale-api-url https://temp-cardano-sandbox.ideascale.com  --event-id 1 --campaign-group-id 87 --stage-id 4573
```
Imported 2 proposals as expected.

fix: Fix IdeaScale importer bugs | NPG-7381

---

utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
utilities/ideascale-importer/ideascale_importer/ideascale/importer.py

* Makes Ideascale importer log an error instead of throwing an exception.
- Ran the ideascale importer with a campaign that has no tagline.

chore: Better error messages in ideascale importer | NPG-7753

---

book/src/07_web_api/openapi/core_backend_api.yaml
src/cat-data-service/src/service/v1/event/objective/mod.rs
src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
src/cat-data-service/src/service/v1/search.rs
src/cat-data-service/src/types/objective.rs
src/cat-data-service/src/types/proposal.rs
src/event-db/migrations/V3__objective_tables.sql
src/event-db/migrations/V4__proposal_tables.sql
src/event-db/src/queries/event/objective.rs
src/event-db/src/queries/event/proposal.rs
src/event-db/src/queries/search.rs
src/event-db/src/types/objective.rs
src/event-db/src/types/proposal.rs

Added new `deleted` field for `Proposal` and `Objective` types and added corresponded columns into the event-db. This new data added to handle some corner cases with importing from  ideascale service.

feat: Add new deleted fields for Proposal and Objective types | NPG-7499

---

src/event-db/src/lib.rs

Change event-db schema version to 9 so it works after the removal of the vit-ss compatibility tables.

chore: Correct event-db schema version | NPG-7769

---

src/cat-data-service/Cargo.toml
src/cat-data-service/README.md
src/cat-data-service/src/cli.rs
src/cat-data-service/src/logger.rs
src/cat-data-service/src/settings.rs

Added different logs formatting as:
- `full`, default human readable format
- `json`,  full JSON format
- `compact`, human readable less verbose output format

feat: Added different logs formatting for cat-data-service | NPG-5779

---

.prettierrc
flake.lock
nix/automation/devshells.nix

Fixes #513. This just gets the devshell working again, which is still being used. The remaining packaging Nix code will be removed after Fund10.

build: updates nixpkgs to include latest rustc | NPG-0000

---

Earthfile
services/voting-node/Earthfile
utilities/ideascale-importer/Earthfile

fix: use debian stable (currently bookworm) slim image for rust toolchain

fix: Use zlib1g-dev instead of lib32z-dev | NPG-0000

---

services/voting-node/Earthfile

This fixes the current issue on #523. However, I do wonder if `build-essential` is actually required in the final container?

build: adds missing build-time deps to voting-node | NPG-0000

---

services/voting-node/Earthfile
utilities/ideascale-importer/Earthfile

`mv` will fail depending on the underlying filesystem of the volume used by docker for its volumes.
See: https://superuser.com/questions/1409618/renaming-a-file-with-mv-cannot-move-to-a-subdirectory-of-itself
This was failing for me,  took forever to work it out what was actually happening.
That error report would indicate this will cause cross platform issues with the build.  So lets not use `mv` in future.

fix(earthly): `mv` is buggy in debian | NPG-0000

---

src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/sve_snapshot.rs
src/catalyst-toolbox/snapshot-lib/src/sve.rs

Fix conversion lovelace to ADA for catalyst-toolbox sve-snapshot. Now the conversion to ada is done on the total voting power. Also fixed the docs has they were unclear on what the --lovelace option does
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

fix: Lovelace rounding and docs catalyst toolbox | NPG-000

---

src/jormungandr/jormungandr/Cargo.toml

Add the `prometheus-metrics` feature to the set of defaults in jormungandr.

chore: Enable prometheus metrics in jormungandr by default | NPG-000

---

src/catalyst-toolbox/snapshot-lib/src/lib.rs
src/catalyst-toolbox/snapshot-lib/src/sve.rs
utilities/snapshot-check/snapshot-check.py

Catalyst toolbox `snapshot` and `sve-snapshot` commands were both (with different code paths) excluding individual registrations with < threshold ada voting power.
This meant that multiple registrations to the same voting key would have missing voting power if any of those individual registrations were < the threshold.  This change does that check only on the cumulative total of all voting power.
The `utilities/snapshot-check/snapshot-check.py` was sued to validate the voting power is properly being calculated.
The `utilities/snapshot-check/compar_snapshot.py` was used to compare a full processed snapshot with an SVE one.
Old snapshots fail to validate, new ones after these changes validate correctly.

fix(catalyst-toolbox): Count missing voting power | NPG-0000

---

src/jormungandr/jormungandr/src/fragment/pool.rs
src/jormungandr/jormungandr/src/metrics/backends/prometheus_exporter.rs

Update a couple of log messages to clarify fragments rejected from the mempool.
Convert `lastBlockTx` prometheus metric from being a gauge into counter.
Add docstrings to clarify the meaning of prometheus metrics related to transactions.

chore: Observability improvements to node logs and metrics | NPG-7984

---

containers/book/Earthfile
containers/book/build-db-diagrams.sh
containers/book/build-mdbook.sh

fix: add rustfmt to run rustdoc-tests.
feat: retry commands in entry scripts up to 6 times

chore: Necessary fixes to earthly book building | NPG-000

---

.github/workflows/cordova_publish.yml

Fix cordova package publishing

fix: Cordova publshing | NPG-8179

---

src/vit-testing/Earthfile

Adding a earthfile to vit-testing. This is needed to enable the build of backend artifacts in the catalyst-artifacts repo
Runned on my local machine
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

feat: Add earthfile for vit-testing | NPG-0000

---

services/voting-node/voting_node/importer.py
services/voting-node/voting_node/main.py
utilities/ideascale-importer/ideascale_importer/snapshot_importer.py

This PR adds "eligible voters" metric to the snapshot importer logs as being the amount of wallets able to vote.
Executed the voting node + snapshot importer locally.

chore: Add eligible voters snapshot metric | NPG-0000

---

Cargo.lock
src/cat-data-service/Earthfile
src/cat-data-service/src/cli.rs
src/cat-data-service/src/legacy_service/health.rs
src/cat-data-service/src/legacy_service/mod.rs
src/cat-data-service/src/legacy_service/v0/fund.rs
src/cat-data-service/src/legacy_service/v1/event/ballots.rs
src/cat-data-service/src/legacy_service/v1/event/mod.rs
src/cat-data-service/src/legacy_service/v1/event/objective/ballots.rs
src/cat-data-service/src/legacy_service/v1/event/objective/mod.rs
src/cat-data-service/src/legacy_service/v1/event/objective/proposal/ballot.rs
src/cat-data-service/src/legacy_service/v1/event/objective/proposal/mod.rs
src/cat-data-service/src/legacy_service/v1/event/objective/proposal/review.rs
src/cat-data-service/src/legacy_service/v1/event/objective/review_type.rs
src/cat-data-service/src/legacy_service/v1/registration.rs
src/cat-data-service/src/legacy_service/v1/search.rs
src/cat-data-service/src/service/api/health/mod.rs
src/cat-data-service/src/service/api/health/ready_get.rs
src/cat-data-service/src/service/api/health/retry_after_put.rs
src/cat-data-service/src/service/api/registration/mod.rs
src/cat-data-service/src/service/api/test_endpoints/test_get.rs
src/cat-data-service/src/service/common/responses/resp_4xx.rs
src/cat-data-service/src/service/common/responses/resp_5xx.rs
src/cat-data-service/src/settings.rs
src/cat-data-service/src/state/mod.rs
src/event-db/Cargo.toml
src/event-db/src/error.rs
src/event-db/src/lib.rs
src/event-db/src/queries/mod.rs

Allow `cat-data-service` to run without connection to DB, logging errors and having a configurable Retry-After header of a 503 response code.
All endpoints attempt to get a connection if none is available.
- Hardware:
- Toolchain:
- SDK:

feat: Handle DB connection timeouts | NPG-000

---

src/sign/README.md
src/sign/src/fragment.rs
src/sign/src/main.rs

add epoch and slot for testing

feat: (fragment generator): add epoch and slot | NPG-000

---

src/catalyst-toolbox/catalyst-toolbox/src/proposal_score/mod.rs

Updated proposal community score calculation, add rounding to 1 decimal place.
So now with the previous calculation result is `5.799999999999999` it will be rounded to `5.8`,
and if result is `5.449999999999999` to `5.4`.

feat: Proposal score calculation, add rounding to 1 decimal place | NPG-8046

---

src/event-db/stage_data/dev/00001_fund11_event.sql
src/event-db/stage_data/dev/00002_fund11_params.sql
src/event-db/stage_data/testnet/00001_fund10_event.sql
src/event-db/stage_data/testnet/00002_fund10_ideascale_params.sql

Fix duplicate key errors by changing stage_data SQL statements to  upsert event and config data instead of inserting.
Closes #500.

chore(fix-stage-data-sql): Upsert stage data | NPG-0000

---

src/event-db/stage_data/dev/00001_fund11_event.sql

- Hardware:
- Toolchain:
- SDK:

chore: extends dev environment fund dates

---

Cargo.lock
src/sign/Cargo.toml
src/sign/README.md
src/sign/src/fragment.rs
src/sign/src/main.rs
src/sign/src/network.rs

In proof systems, provers and the verifiers rely on a common set of parameters, sometimes referred to as the common reference string (CRS).
we are using the the DigestOf<Blake2b256, VotePlan>; as the CRS
align with on the fly load tester updates

fix: crs hex::decode  | NPG-000

---

src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/snapshot/mod.rs
src/jormungandr/jcli/src/jcli_lib/utils/output_file.rs
utilities/ideascale-importer/ideascale_importer/snapshot_importer.py

This PR makes the snapshot importer parse `catalyst-toolbox`'s output correctly.
I also fixed `catalyst-toolbox` creating the summary file in the current directory instead of in the same dir as the output file.
Closes #634.

fix: Make the snapshot importer compatible with the latest catalyst-toolbox output | NPG-0000

---

utilities/ideascale-importer/ideascale_importer/cli/snapshot.py
utilities/ideascale-importer/ideascale_importer/snapshot_importer.py

Removes GVC integration and DRep functionality from the DBSync snapshot importer.
This removes DRep-related command-line arguments.
Closes #646 

feat(dbsync snapshot): Remove GVC and DRep functionality from importer | NPG-000

---

src/event-db/stage_data/dev/00002_fund11_params.sql
src/event-db/stage_data/prod/00002_fund11_params.sql

Updates `stage_data` F11 params.
expected)

feat: Update stage data params for f11 | NPG-000

---

utilities/ideascale-importer/ideascale_importer/cli/snapshot.py
utilities/ideascale-importer/ideascale_importer/snapshot_importer.py

Changes how voter contribution is uploaded to DB by keeping track of the unique key constraint tuple, and processing the network with the highest priority first.
Duplicate records are ignored and an error is logged.
break: CLI option for `network_ids` help docs updated to specify the valid network names.

fix: Handle duplicate key violation in voter contributions | NPG-000

---

src/chain-libs/chain-impl-mockchain/src/accounting/account/spending.rs

NOT PRODUCTION CODE
The following is our[ production chain-libs](https://github.com/input-output-hk/chain-libs/tree/catalyst-fund9-gold)
We have removed spending counter logic long ago due to inherent flaws in the context of correctness. Audit tooling on cat core needs to reflect this to perform a correct offline tally without errors hence removing the checks.

fix(rm spending counter tests): audit tooling f11

---

src/catalyst-toolbox/catalyst-toolbox/scripts/python/proposers_rewards.py
src/catalyst-toolbox/catalyst-toolbox/scripts/python/requirements.txt

This PR adapts the script for the calculation of fund winners.
- A new option to apply the yes/abstain vote is included
- "Sponsored by Leftovers" calculation is included in the script
- Specific categories can be excluded from this
- Winner list with project IDS is automatically generated and exported
- Proposers/Co-proposers emails are automatically pulled from Ideascale (optional)
- Threshold logic fixed and adapted for yes/abstain vote  
- Hardware:
- Toolchain:
- SDK:
**List of new …

feat: Adapt winners calculation for yes,abstain choices | NPG-8970

---

.github/workflows/rust.yml
containers/event-db-migrations/entry.sh
src/event-db/setup/setup-db.sql
src/event-db/stage_data/dev/00002_fund100_params.sql

This PR addresses the following issues:
1. We no longer have a dependency on graphql, so it removes all init code related to that in the eventdb entrypoint
1. The entrypoint was trying to connect to a database that didn't exist
a. It was changed to connect to the "root" database on initialization (a new input was added for this) 
1. For initialization to work with RDS, the root role must be assigned the role the database is being created with
a. This is a weird RDS requirement where the root role isn't really "super"
1. The debug print statements in the init script were printing out the raw database password every single run
a. Even though our logs are private, this is still a serious issue
b. The debug statements were moved to the entrypoint instead so they could be conditionally …

fix: cleans up eventdb entrypoint and adds fix for RDS | NPG-000

---

src/voting-tools-rs/README.md

Updating a stale `snapshot-tool` Readme.
Providing a guides how to build and run `snapshot-tool` itself and referencing to the `cardano-db-sync` docs for spin upping local instance of the database.

feat: Update snapshot-tool readme | NPG-000

---

src/event-db/stage_data/dev/00001_fund12_event.sql
src/event-db/stage_data/dev/00002_fund12_params.sql

- Hardware:
- Toolchain:
- SDK:

chore: restore event db dev times | NPG-000

---

.github/workflows/ci-test.yml
.github/workflows/ci.yml
docker/voting-node.dockerfile
services/voting-node/Earthfile
utilities/fragment-exporter/Earthfile
utilities/ideascale-importer/Earthfile

Fixes https://github.com/input-output-hk/catalyst-voices/issues/1525
- Hardware:
- Toolchain:
- SDK:

chore: Migrate-ci-to-forge | NPG-000

---

.github/workflows/ci.yml
blueprint.cue
containers/event-db-migrations/blueprint.cue
src/event-db/stage_data/preprod/00001_fund14_event.sql

- **feat: updates preprod times | NPG-000**
- **chore: adds deployment for eventdb migrations**
- Hardware:
- Toolchain:
- SDK:
- Crate A: …

chore: adds eventdb deployment

---

services/voting-node/blueprint.cue

- Hardware:
- Toolchain:
- SDK:

chore: adds voting-node deployment

---

src/event-db/stage_data/dev/00001_fund14_event.sql
src/event-db/stage_data/preprod/00001_fund14_event.sql

- Hardware:
- Toolchain:
- SDK:

chore: update times | NPG-000
