input-output-hk/catalyst-core

- src/jormungandr/testing/hersir/src/config/blockchain.rs
My latest changes broke clippy thus this change to fix it
> make clippy happy

- src/vit-testing/vitup/src/mode/mock/rest/mod.rs
copy of https://github.com/input-output-hk/vit-testing/pull/296
> add challenge type to proposal endpoints

- Cargo.lock
- flake.lock
- flake.nix
- src/chain-wallet-libs/bindings/wallet-uniffi/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-uniffi/src/lib.rs
Adds a trivial flake to get a devshell on nixos and fixes the uniffi build issue
> add flake and fix uniffi

- src/chain-libs/chain-impl-mockchain/src/ledger/ledger.rs
- src/chain-libs/chain-impl-mockchain/src/update.rs
- src/jormungandr/jormungandr-lib/src/interfaces/mod.rs
- src/jormungandr/jormungandr-lib/src/interfaces/updates.rs
- src/jormungandr/jormungandr/src/rest/v0/handlers.rs
- src/jormungandr/jormungandr/src/rest/v0/logic.rs
- src/jormungandr/jormungandr/src/rest/v0/mod.rs
- src/jormungandr/testing/hersir/src/config/blockchain.rs
- src/jormungandr/testing/hersir/src/config/mod.rs
- src/jormungandr/testing/jormungandr-automation/src/jormungandr/legacy/rest.rs
- src/jormungandr/testing/jormungandr-automation/src/jormungandr/rest/mod.rs
- src/jormungandr/testing/jormungandr-automation/src/jormungandr/rest/raw.rs
- src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/bft/update_proposal.rs
Exposed updates/active endpoint for taking out currently active update proposals. Extended one of automation tests which should cover basic functionality
> Expose protocol update voting in REST Api

- src/vit-testing/vitup/docker/demo/Dockerfile
- src/vit-testing/vitup/docker/mock/Dockerfile
adjust dockers for catalyst-core repo. Removing separate repos checkout with single one
> Adjust dockers for vitup

- Cargo.lock
- src/vit-testing/vitup/src/cli/diff.rs
- src/vit-testing/vitup/src/cli/mod.rs
- src/vit-testing/vitup/src/cli/time.rs
- src/vit-testing/vitup/src/error.rs
- src/vit-testing/vitup/src/mode/mock/rest/mod.rs
added new endpoint for mock regarding querying challenges by id and voting group id
> mock update for challenges/{id}/{voting-group-id}

- Cargo.lock
- src/chain-wallet-libs/.github/workflows/ci_integration.yaml
- src/chain-wallet-libs/bindings/wallet-uniffi/Cargo.toml
- src/jormungandr/doc/jcli/certificate.md
- src/jormungandr/doc/jcli/vote.md
Add a documentation about the vote cast transaction generation.
> Vote cast transaction generation doc

- src/vit-servicing-station/doc/api/v0.yaml
Add fixes for the API doc corresponding to the https://editor.swagger.io/
> Vit-servicing-station v0.yaml API doc fixes

- src/jormungandr/explorer/src/api/graphql/mod.rs
- src/jormungandr/explorer/src/db/indexing.rs
- src/jormungandr/testing/jormungandr-automation/resources/explorer/graphql/transactions_by_address.graphql
- src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/address.rs
fix transactionsByAddress query glitch which hangs when querying for inputs, outputs or certificate
> Npg 2869 tx by addr query fix

- src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
- src/chain-wallet-libs/bindings/wallet-js/src/lib.rs
- src/chain-wallet-libs/wallet/src/blockchain.rs
- src/jormungandr/jormungandr/src/lib.rs
- src/vit-testing/integration-tests/src/common/registration/starter.rs
- src/vit-testing/integration-tests/src/common/snapshot/mock.rs
- src/vit-testing/integration-tests/src/component/snapshot/testnet.rs
- src/vit-testing/integration-tests/src/e2e/testnet.rs
- src/vit-testing/registration-service/src/client/mod.rs
fix compilation issues on command:
`cargo test --no-run --all-features`
and
`cargo clippy --all-targets`
> Fix test compilation issues

- src/jormungandr/explorer/src/logging.rs
- src/jormungandr/testing/jormungandr-automation/resources/explorer/graphql/allblocks.graphql
- src/jormungandr/testing/jormungandr-automation/resources/explorer/graphql/block_by_id.graphql
- src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/all_blocks_verifier.rs
- src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/block_by_id_verifier.rs
- src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/block.rs
- src/vit-testing/vitup/src/mode/mock/rest/vit_ss.rs
> NPG 3274 verify ad update test

- install-all.sh
Took 1 hr 17 mins to run on my local box, but cargo doesn't complain (except for a temporary glitch in the vitup code).
> Update top-level script to build/test/install everything in the monorepo

- src/vit-testing/vitup/src/config/initials/mod.rs
Which fixes the problem voting app experience when trying to deserialize wallet definition
> add custom serizalizer for Role enum in vitup config

- src/vit-testing/mainnet-lib/src/wallet/registration.rs
- src/voting-tools-rs/src/logic.rs
- src/voting-tools-rs/src/testing/e2e/init.rs
- src/voting-tools-rs/src/testing/functional/mod.rs
- src/voting-tools-rs/src/testing/test_api/fake.rs
- src/voting-tools-rs/src/testing/test_api/output_assertions.rs
I took this pleasure to implement delegation handling in voting tools as lack of this functionality caused some problems in tests.
Added one functional tests for verifications
> Implement delegation in voting tools

- book/src/core-ledger-doc/advanced/04_vote_fragments_voteplan_blockchain_relationships.md
Things I've found out from my recent task related to `chain_proposal_id` .
> add information about chain_proposal_id field

- .github/ISSUE_TEMPLATE/feature_request.md
> Add feature template

- src/chain-wallet-libs/CHANGELOG.md
- src/chain-wallet-libs/bindings/wallet-cordova/package.json
- src/chain-wallet-libs/bindings/wallet-cordova/plugin.xml
- src/chain-wallet-libs/bindings/wallet-cordova/tests/package.json
- src/chain-wallet-libs/bindings/wallet-cordova/tests/plugin.xml
- src/chain-wallet-libs/bindings/wallet-core/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-uniffi/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json
- src/chain-wallet-libs/chain-path-derivation/Cargo.toml
- src/chain-wallet-libs/hdkeygen/Cargo.toml
- src/chain-wallet-libs/symmetric-cipher/Cargo.toml
- src/chain-wallet-libs/wallet/Cargo.toml
Update chain-wallet-libs version from 0.8.1 to 0.8.2. It is needed to fix publishing js package issue https://github.com/input-output-hk/catalyst-core/actions/runs/3731576993/jobs/6329967793
just a small versioning update, no new tests are needed.
> Update chain-wallet-libs version

- .github/workflows/build.yml
- .github/workflows/ci_tests.yml
- Add cancelation of previous CI jobs
- Update build workflow
> Cancel previous CI jobs

- .github/workflows/js_wallet_publish.yml
- Cargo.lock
- src/chain-wallet-libs/bindings/wallet-cordova/package.json
- src/chain-wallet-libs/bindings/wallet-cordova/plugin.xml
- src/chain-wallet-libs/bindings/wallet-cordova/tests/package.json
- src/chain-wallet-libs/bindings/wallet-cordova/tests/plugin.xml
- src/chain-wallet-libs/bindings/wallet-core/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-uniffi/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json
- src/chain-wallet-libs/chain-path-derivation/Cargo.toml
- src/chain-wallet-libs/hdkeygen/Cargo.toml
- src/chain-wallet-libs/symmetric-cipher/Cargo.toml
- src/chain-wallet-libs/wallet/Cargo.toml
Simple cleanup of the wallet-js npm package publishing process
> Update wallet-js CD job

- .github/workflows/nix.yml
- flake.lock
- flake.nix
This is significantly more secure than using static tokens.
> build: adds OIDC authentication for AWS

- .github/workflows/build.yml
- .github/workflows/ci_tests.yml
- Ignore changes in the `book` and `nix` folders in the `build` and `ci_tests` workflows.
> Update build and ci_tests workflows

- Cargo.lock
- src/jormungandr/jormungandr/src/network/p2p/comm/peer_map.rs
- src/jormungandr/jormungandr/src/network/subscription.rs
some small comments / changes to improve readability.
> add comments for clarity

- Cargo.lock
- src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
- src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json
- src/chain-wallet-libs/bindings/wallet-wasm-js/src/certificates/vote_cast.rs
Fixing wallet-js interfaces to be correspond to the CIP-62.
Also fix a bug related to the private vote cast generation
> Fix wallet-js interface, fix bug with the private casting

- .github/workflows/branch-delete-cleanup.yml
- .github/workflows/gh-pages.yml
- .github/workflows/mdlint-changed.yml
- .github/workflows/rust.yml
**Motivation**: it's often confusing to understand and find the proper CI job to make it required. This PR hopefully improves it.
> refactor(ci): naming

- .std/automation/devshells/dev/shell-profile
@stevenj Somehow your commits are including this file :)
> fix: removes .std

- Cargo.lock
- Cargo.toml
- src/cat-data-service/Cargo.toml
- src/cat-data-service/README.md
- src/cat-data-service/src/cli.rs
- src/cat-data-service/src/logger.rs
- src/cat-data-service/src/main.rs
- src/cat-data-service/src/service/mod.rs
- src/cat-data-service/src/service/v0/mod.rs
- src/cat-data-service/src/service/v0/snapshot/delegator.rs
- src/cat-data-service/src/service/v0/snapshot/mod.rs
- src/cat-data-service/src/service/v0/snapshot/voter.rs
- src/cat-data-service/src/settings.rs
- src/cat-data-service/src/v0/mod.rs
Add an initial implementation of the Catalyst Event Data service. Added axum service initialization with clap and tracing
> feat: NPG-5482 Initialize "Catalyst Event Data" service

- Cargo.lock
- src/event-db/migrations/V2__event_tables.sql
- src/event-db/migrations/V9__catalyst_automation.sql
Couple of fixes and change definition of primary key for `voting_node` table.
> fix: Minor changes to migrations

- utilities/ideascale-importer/ideascale_importer/ideascale/client.py
- utilities/ideascale-importer/ideascale_importer/ideascale/importer/__init__.py
- fix: IdeaScale client data was being discarded
- refactor: Upsert challenges and proposals in IdeaScale importer
> fix: Python IdeaScale data importer should upsert data

- book/src/07_web_api/openapi/core_backend_api.yaml
- src/cat-data-service/src/service/v1/event.rs
- src/event-db/src/queries/event.rs
- src/event-db/src/types/event.rs
- src/vit-servicing-station/vit-servicing-station-lib/src/v0/context.rs
- src/vit-testing/integration-tests/src/e2e/rewards/rewards_scenarios.rs
Final fixes for the events endpoints which were initially implemented in this PR: https://github.com/input-output-hk/catalyst-core/pull/311.
Added registration query, some fixes.
> feat: NPG-5790, NPG-5815 add new event's endpoint and db queries (part 2)

- src/event-db/Readme.md
> docs(event-db): Add table of content

- src/cat-data-service/src/service/v1/event/mod.rs
- src/cat-data-service/src/service/v1/event/proposal.rs
- src/event-db/src/types/event/mod.rs
- src/event-db/src/types/event/proposal.rs
It is a first PR where I just added a Proposal db types.
> feat: NPG-5818 Add Proposal db types

- Earthfile
- containers/event-db-migrations/Earthfile
- containers/event-db-migrations/entry.sh
Starting point for migrations container and an example of testing it in CI
> feat(cicd): Add starting point for migrations container build and CI.

- Makefiles/db.toml
- book/src/07_web_api/openapi/core_backend_api.yaml
- src/event-db/src/queries/event/mod.rs
- src/event-db/src/queries/event/proposal.rs
- src/event-db/src/queries/event/review.rs
- src/event-db/src/types/event/mod.rs
- src/event-db/src/types/event/objective.rs
- src/event-db/src/types/event/proposal.rs
- src/event-db/src/types/event/review.rs
- src/event-db/test_data/proposal_review_table.sql
- src/event-db/test_data/review_rating_table.sql
Add new db queries for reviews
> feat: NPG-5819 Add reviews db queries and types

- book/src/07_web_api/openapi/core_backend_api.yaml
- src/cat-data-service/src/service/mod.rs
- src/cat-data-service/src/service/v1/event/mod.rs
- src/cat-data-service/src/service/v1/event/objective.rs
- src/cat-data-service/src/service/v1/event/proposal.rs
- src/cat-data-service/src/service/v1/event/review.rs
- src/cat-data-service/src/service/v1/mod.rs
- src/cat-data-service/src/service/v1/search.rs
- src/event-db/src/error.rs
- src/event-db/src/queries/event/mod.rs
- src/event-db/src/queries/event/proposal.rs
- src/event-db/src/queries/mod.rs
- src/event-db/src/queries/registration.rs
- src/event-db/src/queries/search.rs
- src/event-db/src/types/mod.rs
- src/event-db/src/types/search.rs
Implement new `api/v1/search` endpoint, add db types and db queries
> feat: NPG-5825 implement `api/v1/search` endpoint

- src/cat-data-service/src/service/v1/event/mod.rs
- src/cat-data-service/src/service/v1/event/objective.rs
- src/cat-data-service/src/service/v1/event/proposal.rs
- src/cat-data-service/src/service/v1/event/review.rs
- src/cat-data-service/src/service/v1/mod.rs
- src/cat-data-service/src/service/v1/search.rs
- src/event-db/src/queries/search.rs
- src/event-db/src/types/search.rs
This PR contains only minor fixes and some updates for the cat-data-service and event-db
> feat: Cat data service cleanup and some fixes

- book/src/07_web_api/openapi/core_backend_api.yaml
- src/cat-data-service/src/service/v1/event/mod.rs
- src/cat-data-service/src/service/v1/event/objective/mod.rs
- src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
- src/cat-data-service/src/service/v1/event/objective/proposal/review.rs
- src/cat-data-service/src/service/v1/event/objective/review_type.rs
- src/cat-data-service/src/service/v1/mod.rs
- src/cat-data-service/src/service/v1/search.rs
- src/event-db/src/queries/event/objective.rs
- src/event-db/src/queries/search.rs
- src/event-db/src/types/event/objective.rs
- src/event-db/src/types/search.rs
Slightly modify cat-data-service API, to be more clear and understandable
> feat: Update cat-data-service API

- .github/workflows/stale-branches.yml
> feat(ci): Create stale-branches.yml

- book/src/07_web_api/openapi/core_backend_api.yaml
> docs(api): Fix typos

- src/cat-data-service/entry.sh
- src/cat-data-service/src/settings.rs
Improve deployment for cat-data-service
> build: Deploy cat-data-service with Earthly | NPG-6324

- book/src/07_web_api/openapi/core_backend_api.yaml
- src/cat-data-service/src/service/v0/fund.rs
- src/cat-data-service/src/service/v0/mod.rs
Added a new `/api/v0/fund` which is a replica of vit-ss `/api/v0/fund` endpoint, needed for backward compatibility.
> feat: Add vit-ss /api/v0/fund endpoint | NPG-6690

- src/event-db/historic_data/fund_10.sql
- utilities/ideascale-importer/README.md
- utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
- utilities/ideascale-importer/ideascale_importer/ideascale/importer.py
Updated ideascale importer, update stage-id argument type from int to List[int]
> feat: Update ideascale importer, update stage-id argument type from int to List[int] | NPG-7499

- .github/pull_request_template.md
- .github/workflows/build.yml
- free space for Linux build
- typo fix
> fix(ci): free space for linux build | NPG-0000

- .github/workflows/build.yml
- .github/workflows/ci-tests-n-coverage.yml
- .github/workflows/rust.yml
bump to 1.71 to fix build errors
> chore: fix(upgrade rust version 1.71): bump version | NPG-0000

- utilities/ideascale-importer/Earthfile
Updates earthly build step for ideascale-importer to include lxml system dependencies.
**List of new dependencies**: libxslt-dev libxml2-dev lib32z1-dev
> fix: Update dev dependencies for lxml | NPG-0000

- .github/workflows/ci-test.yml
- Earthfile
- utilities/ideascale-importer/Earthfile
- utilities/ideascale-importer/ideascale_importer/cli/reviews.py
- utilities/ideascale-importer/ideascale_importer/reviews_importer/importer.py
- utilities/ideascale-importer/ideascale_importer/tests/pa.csv
- utilities/ideascale-importer/ideascale_importer/tests/reviews_importer_test.py
- utilities/ideascale-importer/ideascale_importer/tests/test_data/allocations.csv
- Removed allocation step from review's importer, it will be moved as a separate tool later
- Setup test in Earthly
> feat: Update Review's importer, remove allocation step | NPG-8040

- src/event-db/stage_data/dev/00002_testfund_ideascale_params.sql
- utilities/ideascale-importer/Earthfile
- utilities/ideascale-importer/ideascale_importer/cli/reviews.py
- utilities/ideascale-importer/ideascale_importer/reviews_manager/manager.py
- utilities/ideascale-importer/ideascale_importer/reviews_manager/processing/prepare.py
- utilities/ideascale-importer/ideascale_importer/tests/reviews_test.py
- utilities/ideascale-importer/ideascale_importer/tests/test_data/config.json
Cleanup review's importer logic, updated configuration process, load config from file
> feat: Cleanup Review's importer | NPG-7782

- utilities/fragment-exporter/pyproject.toml
Fix `pyproject.toml` in `fragment-exporter`
> fix(fragment-exporter): Update pyproject.toml | NPG-0000

- scripts/tally/private_offline.sh
Small fix to the script to make the result files be identified by the testplan id
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix: Improve offline tally script | NPG-000

- .github/workflows/gh-pages.yml
- Cargo.lock
Fixed github pages docs generation CD job, added uniffi instalation step
> fix: Github pages docs generation | NPG-0000

- src/vit-servicing-station/Earthfile
Adding Earthfile to vit-ss. This is needed to generate the artifacts in the catalyst-artifacts repo
I runned this on my local machine
> feat: Add earthfile to vit-ss | NPG-000

- utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
- utilities/ideascale-importer/ideascale_importer/cli/snapshot.py
- utilities/ideascale-importer/ideascale_importer/snapshot_importer.py
- utilities/ideascale-importer/ideascale_importer/utils.py
I ran the snapshot importer with local tools and via SSH.
> feat: Add snapshot analysis metrics as json logs in voting node ideascale importer | NPG-8136

- src/vit-servicing-station/Earthfile
- src/vit-testing/Earthfile
Fixing a path in Earthfile
- Hardware:
- Toolchain:
- SDK:
> fix: Earthly path for vit-testing and vitss artifacts | NPG-000

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
- Hardware:
- Toolchain:
- SDK:
> chore: updates CI with latest changes

- src/sign/src/main.rs
> feat: Fix(vote plan id ): decode from hex to bytes | NPG-000

- .github/workflows/ci.yml
- Earthfile
- containers/event-db-migrations/Earthfile
- services/voting-node/Earthfile
- src/cat-data-service/Earthfile
- src/event-db/Earthfile
- utilities/fragment-exporter/Earthfile
- utilities/ideascale-importer/Earthfile
- Hardware:
- Toolchain:
- SDK:
> chore: upgrades CI

- utilities/ideascale-importer/ideascale_importer/snapshot_importer.py
Updates call to catalyst-toolbox snapshot command. Fixes arguments by eliminating `--output-format`.
Closes #632
> fix: Ideascale importer cli args updated for catalyst-toolbox | NPG-000

- utilities/ideascale-importer/ideascale_importer/reviews_manager/processing/types/models.py
This PR updates the fields used to extract Reviewer information from Ideascale for F11.
> fix: Update F11 fields for Ideascale reviews manager | NPG-0000

- src/event-db/stage_data/prod/00001_fund11_event.sql
- src/event-db/stage_data/prod/00002_fund11_params.sql
Adding fund 11 dates
The idea scale importer sql file will be updated in another ticket
Fixes https://github.com/input-output-hk/catalyst-core/issues/639
- Hardware:
- Toolchain:
- SDK:
> feat: Fund11 prod dates | NPG-000

- src/event-db/stage_data/dev/00001_fund11_event.sql
- Hardware:
- Toolchain:
- SDK:
> feat: Update cat data service dates | NPG-000

- src/event-db/stage_data/dev/00001_fund11_event.sql
Updating voting dates to be able to test continous snapshot
- Hardware:
- Toolchain:
- SDK:
> feat: Update voting dates | NPG-000

- src/event-db/stage_data/dev/00001_fund11_event.sql
Updating dates on dev env to test cont snapshot
> fix: update snapshot date | NPG-000

- src/event-db/stage_data/dev/00001_fund11_event.sql
Update fund times for next dryrun
> feat: Update fund times | NPG-000

- Cargo.lock
- src/sign/Cargo.toml
- src/sign/README.md
- src/sign/src/main.rs
add choice flag to vote signer, tied to current jorm config where 0 is NO and 1 is YES in the context of position in array.
> feat: (yay or nay): add choice to current jorm crypto config feat | NPG-000

- src/chain-libs/chain-vote/benches/shvzk.rs
- src/chain-libs/chain-vote/src/committee.rs
- src/chain-libs/chain-vote/src/cryptography/zkps/unit_vector/messages.rs
- src/chain-libs/chain-vote/src/cryptography/zkps/unit_vector/zkp.rs
> feat: refactor(updates for uv zkp):  generation and verification | NPG-000

- scripts/tally/private_offline.sh
Add a small improvement to the tally script, fetching the vote plan id straight from the active plans file
- Hardware:
- Toolchain:
- SDK:
> feat: Tally script improvement | NPG-000

- .github/workflows/rust.yml
> feat: obsolete legacy tests | NPG-000

- src/event-db/stage_data/dev/00001_fund100_event.sql
- src/event-db/stage_data/dev/00002_fund100_params.sql
- src/event-db/stage_data/prod/00001_fund100_event.sql
- src/event-db/stage_data/prod/00002_fund100_params.sql
- Hardware:
- Toolchain:
- SDK:
> feat: Adds fund100 to dev and prod | NPG-000

- src/event-db/stage_data/dev/00001_fund100_event.sql
- Hardware:
- Toolchain:
- SDK:
> fix: Dev cont snapshot time | NPG-000

- .github/workflows/ci.yml
- .github/workflows/rust.yml
- src/event-db/stage_data/dev/00001_fund100_event.sql
- tests/wallet-automation/Earthfile
- Hardware:
- Toolchain:
- SDK:
> chore: updates dev staging data | NPG-000

- services/voting-node/voting_node/importer.py
- Hardware:
- Toolchain:
- SDK:
> fix: removes unused parameter to snapshot importer | NPG-000

- src/event-db/stage_data/dev/00001_fund12_event.sql
- src/event-db/stage_data/dev/00002_fund12_params.sql
Adds Fund12 dates for dryrun
- Hardware:
- Toolchain:
- SDK:
> feat: Adds fund12 dev continuos snap dates | NPG-000

- .github/workflows/build.yml
- src/event-db/stage_data/prod/00001_fund12_event.sql
- src/event-db/stage_data/prod/00002_fund12_params.sql
Adding params for fund12 continuos snapshot
- Hardware:
- Toolchain:
- SDK:
> feat: Adds fund12 cont snapshot | NPG-000

- utilities/ideascale-importer/ideascale_importer/db/__init__.py
- Hardware:
- Toolchain:
- SDK:
> fix: prints connection errors for dbsync

- src/event-db/stage_data/dev/00001_fund12_event.sql
- Hardware:
- Toolchain:
- SDK:
> feat: update times | NPG-000

- utilities/ideascale-importer/ideascale_importer/reviews_manager/processing/types/models.py
This PR updates the fields used to extract Reviewer information from Ideascale for F12.
> fix: Update F12 fields for Ideascale reviews manager | NPG-0000

- src/event-db/stage_data/dev/00001_fund12_event.sql
Updating dev cont snapshot times
- Hardware:
- Toolchain:
- SDK:
> feat: Update dev cont snap | NPG-000

- services/voting-node/voting_node/helpers.py
Simple comment to indicate the integer limit for `max_voting_power_pct` (aka. `voting_power_cap`).
> fix: Add comments about voting power cap argument | NPG-000

- src/event-db/stage_data/dev/00001_fund12_event.sql
- Hardware:
- Toolchain:
- SDK:
> fix: continuos snapsot voting power cap | NPG-000

- src/event-db/stage_data/dev/00001_fund13_event.sql
- src/event-db/stage_data/dev/00002_fund13_params.sql
Adds fund13 to dev cont snapshot
- Hardware:
- Toolchain:
- SDK:
> chore: adds dev fund13 dates | NPG-000

- src/event-db/stage_data/dev/00001_fund12_event.sql
- src/event-db/stage_data/dev/00002_fund12_params.sql
- Hardware:
- Toolchain:
- SDK:
> chore: restore fund12 times | NPG-000

- src/event-db/stage_data/dev/00001_fund13_event.sql
- src/event-db/stage_data/dev/00002_fund13_params.sql
- Hardware:
- Toolchain:
- SDK:
> feat: update dev times | NPG-000

- src/event-db/stage_data/prod/00001_fund13_event.sql
- src/event-db/stage_data/prod/00002_fund13_params.sql
- Hardware:
- Toolchain:
- SDK:
> feat: Adds fund13 prod cont snap | NPG-000

- src/event-db/stage_data/dev/00001_fund13_event.sql
Update cont snapshot times for dev
- Hardware:
- Toolchain:
- SDK:
> chore: Update dev snapshot times | NPG-000

- src/event-db/stage_data/preprod/00001_fund13_event.sql
- src/event-db/stage_data/preprod/00002_fund13_params.sql
- Hardware:
- Toolchain:
- SDK:
> chore: Update preprod snapshot times | NPG-000

- src/event-db/stage_data/dev/00001_fund13_event.sql
- Hardware:
- Toolchain:
- SDK:
> chore: update dryrun times | NPG-000

- containers/event-db-migrations/Earthfile
Bump the refinery version to fix the build in catalyst-reviews.
> fix: Bump refinery version | NPG-000

- src/event-db/stage_data/dev/00001_fund14_event.sql
- src/event-db/stage_data/dev/00002_fund14_params.sql
- Hardware:
- Toolchain:
- SDK:
> feat: updates continuos snapshot data | NPG-000

- src/event-db/stage_data/preprod/00001_fund14_event.sql
- src/event-db/stage_data/preprod/00002_fund14_params.sql
- Hardware:
- Toolchain:
- SDK:
> chore: Update times | NPG-000

- src/event-db/stage_data/dev/00001_fund14_event.sql
- Hardware:
- Toolchain:
- SDK:
> chore: update times | NPG-0000

- src/event-db/stage_data/preprod/00001_fund14_event.sql
- Hardware:
- Toolchain:
- SDK:
> chore: update eventdb migrations | NPG-000

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
- blueprint.cue
- containers/event-db-migrations/blueprint.cue
- services/voting-node/blueprint.cue
- src/event-db/stage_data/preprod/00001_fund14_event.sql
- **feat: updates preprod times | NPG-000**
- **chore: adds deployment for eventdb migrations**
- **chore: bumps forge version**
- **chore: fixes secret reference**
- **chore: cleanup**
- **chore: updates forge again**
- Hardware:
- Toolchain:
- SDK:
Provide a list of …
> chore: updates forge to latest version

- src/event-db/stage_data/dev/00001_fund14_event.sql
- Hardware:
- Toolchain:
- SDK:
> chore: updates fund dates for dev environment

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
- blueprint.cue
- Hardware:
- Toolchain:
- SDK:
> chore: updates forge and ci versions | NPG-0000

- .github/workflows/ci-test.yml
- .github/workflows/ci.yml
- blueprint.cue
- Hardware:
- Toolchain:
- SDK:
> ci(general): bumps forge to v0.19.1 and ci to v1.8.1 | NPG-000

- src/catalyst-toolbox/catalyst-toolbox/scripts/python/proposers_rewards.py
Apply gamma to single voter to calculate total stake threshold.
> feat: Apply gamma to single voter to calculate total stake threshold | NPG-000
